[workspace]
authors = ["yihan2588 <167504939+yihan2588@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "lab"
lab = "jupyterlab"

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
