[workspace]
authors = ["yihan2588 <167504939+yihan2588@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pixi-cuda-lesson"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.5,<3.14"
jupyterlab = ">=4.4.5,<5"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"

[tasks]
lab = { cmd = "jupyter lab", description = "Launch JupyterLab" }
start = { depends-on = [{ task = "lab" }], description = "Start exploring the Pixi project" }
