[workspace]
authors = ["yihan2588 <167504939+yihan2588@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "dir-strucuture"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
